apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  containers:
  - name: nginx
    image: nginx
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: run
      mountPath: /var/run
    - name: log
      mountPath: /var/log/nginx
    - name: cache
      mountPath: /var/cache/nginx
  volumes:
  - name: run
    emptyDir: {}
  - name: log
    emptyDir: {}
  - name: cache
    emptyDir: {}
